sudo: false

language: php

php:
    - 7.4
    - 7.3
    - 7.2
    - 7.1

install:
    - make vendor/installed
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - make tools/phpunit tools/readme-tester PHIVE_CMD="php phive.phar"

script:
    - tools/phpunit
    - tools/readme-tester README.md
